version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: refresh_tokens_mongoose_exmaple
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
