
DELETE http://localhost:3030/refresh-tokens/1?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOjEsImlhdCI6MTU5NTQzMzI1MSwiZXhwIjoxNjI2NTM3MjUxLCJhdWQiOiJodHRwczovL2V4YW1wbGUuY29tIiwiaXNzIjoiZXhhbXBsZSIsImp0aSI6ImRmYmI2MWYwLTY2ZTYtNGUzYS04NGNhLTUwZTNlNTdiYzhkYSJ9.s7gJhUw7SRHclhJ5iO6Z-KOndY4LJSFFWsCIUOZwIrE
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpZCI6IjEiLCJpYXQiOjE1OTU0MzMyODksImV4cCI6MTU5NTUxOTY4OSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwianRpIjoiM2MyYmM0YTAtZDViMi00ZjU3LTgxNGUtYzdlZDgwNjE5MmRiIn0.Shl29WZ7AzaDjiKU2lJfZzZH6NP1Ug5vXJTXnfl0hQo
