
DELETE http://localhost:3030/refresh-tokens/5f0e27253c1964dd130ee34e?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiI1ZjBlMjcyNTNjMTk2NGRkMTMwZWUzNGUiLCJpYXQiOjE1OTQ3NjMwNTIsImV4cCI6MTYyNTg2NzA1MiwiYXVkIjoiaHR0cHM6Ly9leGFtcGxlLmNvbSIsImlzcyI6ImV4YW1wbGUiLCJqdGkiOiI5ODdkYTYyZC0wMGVlLTRmM2YtOTg2My1iMjQyOWI4MzI4ZmIifQ.x_aKa_DLnhBfKCgYy1TVANQumrB2f4y6xrxoj0HU5x4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJfaWQiOiI1ZjBlMjcyNTNjMTk2NGRkMTMwZWUzNGUiLCJpYXQiOjE1OTQ3NjMwODYsImV4cCI6MTU5NDg0OTQ4NiwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwianRpIjoiMjFhYjg4YjgtNDY4Yi00YTM4LTg4Y2EtMTU1ZThlMDJhMWE3In0.twWSasMF8f2PAUAov_rXAyjTqEKxLI5Agy7jTu0Q66k
