
POST http://localhost:3030/refresh-tokens
Content-Type: application/json

{
  "_id": "kHrm7GIcmGpp2uAl",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiJrSHJtN0dJY21HcHAydUFsIiwiaWF0IjoxNTk0NjI1MDM3LCJleHAiOjE2MjU3MjkwMzcsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiNzkyZTA4ZGEtMjBjYi00NGI4LThhNDMtNGJkMzljMjY1NzhiIn0.4Ffvi2vVkeHjkPsOzC-Bx8mL7WgklNWpeUCgoGGGpKo"
}

