
DELETE http://localhost:3030/refresh-tokens/qsl3SMIBCFoBE3UK?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiJxc2wzU01JQkNGb0JFM1VLIiwiaWF0IjoxNTk0NTk5NDY3LCJleHAiOjE2MjU3MDM0NjcsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiN2RjMmFiM2MtODVlOS00Y2JkLWFkNzgtZDkyYmQ4MTY2ZDczIn0.F6Snpkc5A9PELSuVh1_WkjU1ck4VKvMBixy3GdZj0Z4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJfaWQiOiJxc2wzU01JQkNGb0JFM1VLIiwiaWF0IjoxNTk0NTk3NzE4LCJleHAiOjE1OTQ2ODQxMTgsImF1ZCI6Imh0dHBzOi8veW91cmRvbWFpbi5jb20iLCJpc3MiOiJmZWF0aGVycyIsImp0aSI6IjZhOGU1N2E1LWU3NTgtNGRiZC04MmRjLTNmZDgyMmEwNmVlOSJ9.CMpH4WuLl6ofQAHwXVLj8xd2rt1p662b8OzYXkjO_bc
