
DELETE http://localhost:3030/refresh-tokens/kHrm7GIcmGpp2uAl?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiJrSHJtN0dJY21HcHAydUFsIiwiaWF0IjoxNTk0NjI1MDM3LCJleHAiOjE2MjU3MjkwMzcsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiNzkyZTA4ZGEtMjBjYi00NGI4LThhNDMtNGJkMzljMjY1NzhiIn0.4Ffvi2vVkeHjkPsOzC-Bx8mL7WgklNWpeUCgoGGGpKo
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJfaWQiOiJrSHJtN0dJY21HcHAydUFsIiwiaWF0IjoxNTk0NjI1NDQ5LCJleHAiOjE1OTQ3MTE4NDksImF1ZCI6Imh0dHBzOi8veW91cmRvbWFpbi5jb20iLCJpc3MiOiJmZWF0aGVycyIsImp0aSI6ImU4YTJiNWM4LTA4YmEtNGNmOS05YjM1LTA4ZThjODk3ZWY5MyJ9.zgfMIaDGotUp6a4OEYebguBET0ARsPAqqztiIwx33jA
