
DELETE http://localhost:3030/refresh-tokens/1?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOjEsImlhdCI6MTU5NTg3NjQzMSwiZXhwIjoxNjI2OTgwNDMxLCJhdWQiOiJodHRwczovL2V4YW1wbGUuY29tIiwiaXNzIjoiZXhhbXBsZSIsImp0aSI6ImFiM2VmMzUzLWEyYjMtNDk4NC04YWZiLWVjM2EzZDQxMmQ3YyJ9.UFc-O_1S-g19XUwdv8FET1XwwVefDBj69NQi23Qe_98
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE1OTU4NzY0NjksImV4cCI6MTU5NTk2Mjg2OSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiMSIsImp0aSI6ImE5MzAyNGVjLTUxNWItNDU0OC1hMzA2LTY2NDIyMzU2ODQ5NiJ9.HqzpEDhmLq884CUEi2KqVi76cEJA-7Yr86dStYzEOa4
