
DELETE http://localhost:3030/refresh-tokens/1?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiIxIiwiaWF0IjoxNTk1OTcwNDI1LCJleHAiOjE2MjcwNzQ0MjUsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiMmRhMDlkNzEtY2RiMC00NWE1LWFjNjItODYyZTA0ODRkNGU2In0.QiHu308VhZEoOBa9oBdYLvKAGRQ6_hilSDtFkAWKzvU
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE1OTU5ODEzNjEsImV4cCI6MTU5NjA2Nzc2MSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiMSIsImp0aSI6ImZmYWQ1YTU0LTA0NmEtNDM3YS05OGRmLWZlMjY5M2JhNzkyMyJ9.UJV9dVtUi-nH_CFKME7_yeN9E5JJJWjH2gHg5sourlE
