
DELETE http://localhost:3030/refresh-tokens/1?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOjEsImlhdCI6MTU5NDc2MjI5NSwiZXhwIjoxNjI1ODY2Mjk1LCJhdWQiOiJodHRwczovL2V4YW1wbGUuY29tIiwiaXNzIjoiZXhhbXBsZSIsImp0aSI6ImEzMGUzZGIwLTEyNTMtNDkzMy1hYzRmLWZmYWJiNzUzMzAwYyJ9.Nhs6p2OgGXdZxKIz24IK-Akmcduk7U7XWrdQYW6291k
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpZCI6IjEiLCJpYXQiOjE1OTQ3NjI1MTEsImV4cCI6MTU5NDg0ODkxMSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwianRpIjoiMWVlNWEyM2ItMGU2YS00N2Q2LTkxYzktZjQ2NDEzODg5MjUwIn0.NfHtLqRlfw06FVBnK9Dx50S_MKp5rhWTJY9YV6Ql5oc
