
PATCH http://localhost:3030/refresh-tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTk1OTY0NjI3LCJleHAiOjE1OTYwNTEwMjcsImF1ZCI6Imh0dHBzOi8veW91cmRvbWFpbi5jb20iLCJpc3MiOiJmZWF0aGVycyIsImp0aSI6IjFlMWUzMjk2LTE1ZGUtNDhkNy04YTBjLWExOWE1N2Y2MWVlNCJ9.lU7i-2w3P7OtDhhda74f4OD-hNpq4o9kztCNp1jLxT0
Content-Type: application/json

{
  "id": "1",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOjEsImlhdCI6MTU5NTk2NTYxMiwiZXhwIjoxNjI3MDY5NjEyLCJhdWQiOiJodHRwczovL2V4YW1wbGUuY29tIiwiaXNzIjoiZXhhbXBsZSIsImp0aSI6IjE4OWM0M2U1LTZiMWYtNGFjNi04MWM3LTkwNzAxOWFlZTFjYyJ9.kNAaxlMLdQadD22rAWu0CpnLfAE-QXeAizPJ3OGQ2I0"
}

