
DELETE http://localhost:3030/refresh-tokens/TsbFK9uD7clIwIsR?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiJUc2JGSzl1RDdjbEl3SXNSIiwiaWF0IjoxNTk1NDMyNDMyLCJleHAiOjE2MjY1MzY0MzIsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiMjQwMjcyYWEtNmU3NS00MzFiLTllNDMtMWU4ZDBhMGFiYmE0In0.4s28QlJ-3ZkL6JkGpMHqVbKgfotOnr3LZLvxmE48qbM
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJfaWQiOiJUc2JGSzl1RDdjbEl3SXNSIiwiaWF0IjoxNTk1NDMyNTQyLCJleHAiOjE1OTU1MTg5NDIsImF1ZCI6Imh0dHBzOi8veW91cmRvbWFpbi5jb20iLCJpc3MiOiJmZWF0aGVycyIsImp0aSI6ImFmNjQ0NGZkLTMxMDktNGI0My1iNWU4LTdkNTQxNTY2YTIxYSJ9.cdW-AcmKWCNgp1jpWKJqz-ZqBJzOQ7zxYzCJ3brcIps
