
DELETE http://localhost:3030/refresh-tokens/waVM0pQ26tx1I63Y?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiJ3YVZNMHBRMjZ0eDFJNjNZIiwiaWF0IjoxNTk0NzYyOTA4LCJleHAiOjE2MjU4NjY5MDgsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiMjM2MzQ2NmQtNzE5MS00Mzk1LTk1YmItNGI1OWE4Yjk5M2I1In0.POLQBXzRvzjn8DyBIFXf5h0AjFMI9Llaug2St3pkxyQ
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJfaWQiOiJ3YVZNMHBRMjZ0eDFJNjNZIiwiaWF0IjoxNTk0NzYyOTQ0LCJleHAiOjE1OTQ4NDkzNDQsImF1ZCI6Imh0dHBzOi8veW91cmRvbWFpbi5jb20iLCJpc3MiOiJmZWF0aGVycyIsImp0aSI6IjI2ZGFiOTliLWE3ZGEtNDJhZi1iYzYzLTVhOWE3ODMwODNiNCJ9.1hkhuoD2turL9TVInhO-3ynf8cq5PNvb9jdgf4B_ON4
