
POST http://localhost:3030/refresh-tokens
Content-Type: application/json

{
  "_id": "waVM0pQ26tx1I63Y",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiJ3YVZNMHBRMjZ0eDFJNjNZIiwiaWF0IjoxNTk0NzYyOTA4LCJleHAiOjE2MjU4NjY5MDgsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiMjM2MzQ2NmQtNzE5MS00Mzk1LTk1YmItNGI1OWE4Yjk5M2I1In0.POLQBXzRvzjn8DyBIFXf5h0AjFMI9Llaug2St3pkxyQ"
}

