
POST http://localhost:3030/refresh-tokens
Content-Type: application/json

{
  "_id": "TsbFK9uD7clIwIsR",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6InJlZnJlc2gifQ.eyJzdWIiOiJUc2JGSzl1RDdjbEl3SXNSIiwiaWF0IjoxNTk1NDMyNDMyLCJleHAiOjE2MjY1MzY0MzIsImF1ZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlIiwianRpIjoiMjQwMjcyYWEtNmU3NS00MzFiLTllNDMtMWU4ZDBhMGFiYmE0In0.4s28QlJ-3ZkL6JkGpMHqVbKgfotOnr3LZLvxmE48qbM"
}

