

http://localhost:3030/users/5f0e0b5d457997305ae1e2d7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE1OTQ3NTc3NTUsImV4cCI6MTU5NDg0NDE1NSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiNWYwZTBiNWQ0NTc5OTczMDVhZTFlMmQ3IiwianRpIjoiODEzYmFiYTUtYjNkNC00OTk5LThlMmYtZWEyYmM4MzdiZWE3In0.yOEAICVnrcS22-Sf_ZKsWL72_ecwpbzm-J68TZi35QI
